// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	input "github.com/pedropazello/lojinha-product-catalog-service/internal/application/ports/input"

	mock "github.com/stretchr/testify/mock"

	output "github.com/pedropazello/lojinha-product-catalog-service/internal/application/ports/output"
)

// ICreateProductUseCase is an autogenerated mock type for the ICreateProductUseCase type
type ICreateProductUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: product
func (_m *ICreateProductUseCase) Execute(product *input.ProductData) (*output.ProductData, error) {
	ret := _m.Called(product)

	var r0 *output.ProductData
	if rf, ok := ret.Get(0).(func(*input.ProductData) *output.ProductData); ok {
		r0 = rf(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.ProductData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*input.ProductData) error); ok {
		r1 = rf(product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
