// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDeleteProductUseCase is an autogenerated mock type for the IDeleteProductUseCase type
type IDeleteProductUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: id
func (_m *IDeleteProductUseCase) Execute(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
