// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IFileStorage is an autogenerated mock type for the IFileStorage type
type IFileStorage struct {
	mock.Mock
}

// GetFile provides a mock function with given fields: fileName
func (_m *IFileStorage) GetFile(fileName string) ([]byte, error) {
	ret := _m.Called(fileName)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(fileName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
