// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IImportProductsByFileUseCase is an autogenerated mock type for the IImportProductsByFileUseCase type
type IImportProductsByFileUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: fileName
func (_m *IImportProductsByFileUseCase) Execute(fileName string) error {
	ret := _m.Called(fileName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
