// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	output "github.com/pedropazello/lojinha-product-catalog-service/internal/application/ports/output"
	mock "github.com/stretchr/testify/mock"
)

// IReadFileWithProductsUseCase is an autogenerated mock type for the IReadFileWithProductsUseCase type
type IReadFileWithProductsUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: filePath
func (_m *IReadFileWithProductsUseCase) Execute(filePath string) ([]output.ProductData, []error, error) {
	ret := _m.Called(filePath)

	var r0 []output.ProductData
	if rf, ok := ret.Get(0).(func(string) []output.ProductData); ok {
		r0 = rf(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]output.ProductData)
		}
	}

	var r1 []error
	if rf, ok := ret.Get(1).(func(string) []error); ok {
		r1 = rf(filePath)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(filePath)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
