// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	output "github.com/pedropazello/lojinha-product-catalog-service/src/application/ports/output"
	mock "github.com/stretchr/testify/mock"
)

// IReadProductUseCase is an autogenerated mock type for the IReadProductUseCase type
type IReadProductUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *IReadProductUseCase) Execute() (output.ProductData, error) {
	ret := _m.Called()

	var r0 output.ProductData
	if rf, ok := ret.Get(0).(func() output.ProductData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(output.ProductData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
